### ISSUE TITLE
Address bar click incorrectly detected as 'hidden' rather than 'hidden-awesomebarclick' after opening a new tab

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mikedeboer/shield-search-nudges#10] opened 2018-08-09 07:04 UTC
[Affected versions]:
- Firefox 61.0.1 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the " Search Nudges" add-on (1.4.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- The "Nudges" doorhanger was not triggered before.
- Have the following preferences in the "about:config" page:
"extensions.legacy.enabled" set to true;
create the "extensions.shield-search-nudges.variation" string with the "doshow" value.
- Have the Browser Console open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Open a new tab and click inside the "Address bar".
3. Switch to the Browser Console and observe the last sent event.
  
[Expected result]:
- "general-hidden-awesomebarclick" event is displayed.

[Actual result]:
- "general-hidden" event is displayed.

[Notes]:
- This issue is not reproducible with the "about:home" page, "Home Page" button & with the "Redirect" tip.
- Here is a screen recording with this issue:
![nudges - address bar](https://user-images.githubusercontent.com/31244235/43883347-7dd8a6a8-9bbb-11e8-8aca-411333967ccb.gif)

**Comment by Standard8** [comment] 2018-08-10 15:44
This happens when opening a new tab. When switching to an already opened tab which has about:newtab loaded, it works correctly.

In the create a new tab case, the tab is giving the url bar focus, which although we then click in it, we don't see it as having taken the focus, and hence we log the incorrect item.

This also causes other issues like the study thinking it hasn't ended (#16)

**Comment by SoftVision-CosminMuntean** [comment] 2018-08-20 09:07
I have verified this issue using latest "Search Nudges" version (1.6.0) and the issue is still reproducible on Linux (tested on Ubuntu 16.04 x64 and Arch Linux 4.12). It is reproducible if you open a new tab and also if you switch to an already opened tab.

However, the issue is no longer reproducible on Windows and Mac OS. Considering the fact that it is still reproducible on Linux, I will reopen it.

**Comment by mikedeboer** [comment] 2018-08-20 15:01
Since you are only able to reproduce this on Linux, I'd like to leave this issue open and ship the study with this as a 'known issue' instead.

**Comment by mikedeboer** [comment] 2018-08-21 09:54
Instead, let's close this off to get a clean slate instead, since it's essentially a WONTFIX.

**Closed as completed by mikedeboer** 2018-08-21 09:54 UTC
Labels: [QA]:Wontfix issue
