### ISSUE TITLE
The "Redirection tip" doorhanger in not triggered in "Private Window"

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mikedeboer/shield-search-nudges#12] opened 2018-08-09 12:22 UTC
**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the " Search Nudges" add-on (1.4.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- The "Nudges" doorhanger was not triggered before.
- Have the following preferences in the "about:config" page:
	- "extensions.legacy.enabled" set to true;
	- create the "extensions.shield-search-nudges.variation" string with the "doshow" value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a "Private Window" and navigate to "https://www.google.com/".
3. Observe the behavior.

**[Expected result]:**
- The "Redirection tip" doorhanger is triggered.

**[Actual result]:**
- The "Redirection tip" doorhanger is not triggered at all.

**[Notes]:**
- This issue is not reproducible with the "Onboarding tip" doorhanger.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/43898078-d8cf43ca-9be6-11e8-804f-a7077add793c.gif)

**Comment by Standard8** [comment] 2018-08-10 15:10
Ok, the strange thing here, is that it looks like google is redirecting `google.com` to `https://www.google.com/?gws_rd=ssl`. That's not going to match our current algorithm which expects no parameters on the end...

**Comment by Standard8** [comment] 2018-08-10 15:50
I'm going to mark this as a duplicate of #23, as really the issue is exactly the same.

Duplicate of #23

**Closed as completed by Standard8** 2018-08-10 15:50 UTC
Labels: [QA]:Verified fixed

**Comment by SoftVision-CosminMuntean** [comment] 2018-08-20 09:08
I have verified this issue using latest "Search Nudges" version (1.6.0) and it's no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
