### ISSUE TITLE
The doorhanger is wrongly displayed if it was previously dismissed from the address bar and the browser is restarted

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mikedeboer/shield-search-nudges#16] opened 2018-08-09 15:29 UTC
[Affected versions]:
- Firefox 61.0.2 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the " Search Nudges" add-on (1.4.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- The "Nudges" doorhanger was not triggered before.
- Have the following preferences in the "about:config" page:
"extensions.legacy.enabled" set to true;
create the "extensions.shield-search-nudges.variation" string with the "doshow" value.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Open a new tab and click inside the "Address bar".
3. Restart the browser.
4. Open a new tab and observe the behavior.
  
[Expected result]:
- Activity Stream page is displayed.

[Actual result]:
- Activity Stream page is displayed and the "Nudges" doorhanger appears.

[Notes]:
- This issue is also reproducible for the "about:home" page and for the redirection doorhanger, from partner search pages.
- Here is a screen recording with this issue:

![nudges - doorhanger after restart](https://user-images.githubusercontent.com/31244235/43909039-18b27c9e-9c02-11e8-9f52-9404d24a9ec3.gif)

**Comment by Standard8** [comment] 2018-08-10 15:49
The issue here is the same as the cause of #10, therefore closing as duplicate.

Duplicate of #10.

**Closed as completed by Standard8** 2018-08-10 15:49 UTC
Labels: [QA]:Invalid issue
