### ISSUE TITLE
"General Onboarding" and "Redirect" tips are wrongly displayed during the first session after updating the browser

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mikedeboer/shield-search-nudges#21] opened 2018-08-10 12:27 UTC
[Notes]:
- This issue is reproducible on both "control" and "treatment" branches.
- On "control" branch, the door hanger is not displayed, but the events are still generated in the session following the browser update.
- According to the study's PHD's Acceptance criteria, users should not see any tip during the first session after an upgrade to a new Firefox version. 

[Affected versions]:
- Firefox Release 61.0.2
- Firefox Beta 62.0b15

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Doorhanger Nudges version 1.4.0 addon is installed on an older version of Firefox (61.0)
- The "Nudges" doorhanger was not triggered before.
- Have the following preferences in the "about:config" page:
"extensions.legacy.enabled" set to true;
create the "extensions.shield-search-nudges.variation" string with the "doshow" value.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Hamburger menu" button>Help>About Firefox.
3. Click on the "Restart to Update Firefox" button.
4. Open a new tab and observe the behavior.

[Expected result]:
- The General Onboarding Tip is not displayed.

[Actual result]:
- The General Onboarding Tip is displayed.

[Aditional Notes]:
- Here is a screencast of the issue: https://goo.gl/d9Ft2S

**Comment by Standard8** [comment] 2018-08-10 13:51
I think the test here may be wrong, though I'm not quite sure. Generally I was assuming the shield study is only going to be installed in one version of Firefox, and it won't go through an update cycle. If so, the add-on does handle this as it doesn't prompt when installed straight away.

If we do need to handle this, then we're going to have to add in some sort of additional pref to record the version before and after...

**Comment by SoftVision-CarmenFat** [comment] 2018-08-10 14:18
Yes, you are right that the study is going to be installed in one version of Firefox, but, assuming that the study is going to be launched on 13th of August on Release 61.0.2 and it will be live for a while (6 weeks more precisely), most of the users will update their browsers to 62.0 version in September. 

This is the reason we are currently testing both Beta 62.0b15 and Release 61.0.2 and also the update browser scenario.

**Comment by mikedeboer** [comment] 2018-08-17 11:20
I don't think this is a big issue and weighing the cost of implementing a fix against the severity makes me think of WONTFIXing this one.

**Comment by SoftVision-CosminMuntean** [comment] 2018-08-21 11:07
I have verified this issue using the latest "Search Nudges" version (1.7.0) and the issue is still reproducible.
I have tried the following scenarios and the tips were displayed after each update in the same session:

- updated Firefox 60.0 version to Firefox 61.0.2
- updated Firefox 61.0 to 61.0.2
- updated Beta 62.0b3 to Beta 62.0b18

Considering this I will reopen this issue until a decision is made.

**Comment by mikedeboer** [comment] 2018-08-21 16:02
Alright, if this is still happening, than I have to make this a WONTFIX; apparently it's not simple enough to work out this functionality. We should have this as a core feature of the browser, not something unique to this addon.

**Closed as completed** 2018-08-21 16:08 UTC
Labels: [QA]:Wontfix issue
